name: "Release"
on:
  release:
    types:
      - created

jobs:
  nix-release:
    name: 'Release Nix expression'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v12

      - name: Upload release.nix
        id: create-release-nix
        uses: ttuegel/upload-release.nix@v0.4
