name: "Release"
on:
  release:
    types:
      - created

jobs:
  nix-release:
    name: 'Release Nix expression'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v12

      - name: Create release.nix
        id: create-release-nix
        uses: ttuegel/upload-release.nix@v0.3

      - name: Upload release expression
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.create-release-nix.outputs.asset_path }}
          asset_name: release.nix
          asset_content_type: text/plain

