name: "Release"
on:
  release:
    types:
      - created

jobs:
  nix-release:
    name: 'Release Nix expression'
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v12

      - name: Upload release.nix
        uses: ttuegel/upload-release.nix@v0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
